fix(template): use task_runner instead of deprecated use_temporal variable
Fixed lich init failure when selecting task_runner=temporal. Template files
were using the old variable name 'cookiecutter.use_temporal == yes' instead
of 'cookiecutter.task_runner == temporal'.

Affected files:
- template/{{cookiecutter.project_slug}}/agentlog.md
- template/hooks/post_gen_project.py
- template/{{cookiecutter.project_slug}}/docker-compose.yml
- template/{{cookiecutter.project_slug}}/QUICK_START.md

Fixes template error: 'collections.OrderedDict object' has no attribute 'use_temporal'